- name: IP Spoofing protection
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
    sysctl_set: yes
    state: present
    reload: no

- name: Ignore ICMP broadcast requests
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    sysctl_set: yes
    state: present
    reload: no

- name: Disable source packet routing
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv6.conf.default.accept_source_route
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- name: Ignore send redirects
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- name: Block SYN attacks
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 2048
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_synack_retries
    value: 2
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_syn_retries
    value: 5
    sysctl_set: yes
    state: present
    reload: no

- name: Log Martians
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    sysctl_set: yes
    state: present
    reload: no

- name: Ignore ICMP redirects
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: no

- name: Ignore Directed pings && reload sysctl
  sysctl:
    name: net.ipv4.icmp_echo_ignore_all
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
