---
- name: Install python on hosts
  hosts: rancher
  remote_user: root
  # remote_user: azureuser
  # become: yes
  # become_method: sudo
  gather_facts: False

  tasks:
  - name: Install python on host
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
    register: output
    changed_when: output.stdout != ""

- name: Create a secure install then setup docker
  hosts: rancher
  remote_user: root
  # remote_user: azureuser
  # become: yes
  # become_method: sudo

  roles:
  - role: common
  - role: networking
  - role: ufw
  - role: docker
    when: ansible_architecture != "aarch64"
  - role: docker_arm
    when: ansible_architecture == "aarch64"
  - role: rancher
