- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Secure shared memory
  mount:
    path: /run/shm
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noexec,nosuid
    state: present




