# https://github.com/ansible/ansible/issues/21348
#- name: Start (or restart) rancher container without letsencrypt
#  docker_container:
#    name: rancher
#    image: rancher/rancher:latest
#    state: started
#    restart: yes
#    restart_policy: unless-stopped
#    devices:
#     - "/opt/rancher:/var/lib/rancher"
#    ports:
#     - "80:80"
#     - "443:443"
#    command: ["--acme-domain", "{{ acme_domain }}"]

- name: Delete previous rancher containers
  command: bash -c "(docker stop rancher && docker rm rancher) || true"
  ignore_errors: yes

- name: Create rancher container with letsencrypt
  command: docker run -d --name rancher --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:latest --acme-domain {{ acme_domain }}
  when: acme_domain != "unset"

- name: Create rancher container without letsencrypt
  command: docker run -d --name rancher --restart=unless-stopped -p 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:latest
  when: acme_domain == "unset"

- debug:
    msg:
      - "Rancher deployed successfully"
      - "Access your server at https://{{ ansible_default_ipv4.address }}/"